### ISSUE TITLE
The timestamp generated in the token is wrong! Using the DAY-OF-WEEK (1-7) not the DATE

### ISSUE THREAD

**Issue by grempe** [dpk/hashcash.js#3]
Using this line of code:

https://github.com/dpk/hashcash.js/blob/master/hashcash.js#L42

You are currently creating a timestamp for the token that is:

YY:MM:DAYOFWEEK

When it should be:

YY:MM:DD

e.g. if I run this code on a Saturday, the `date.getDay() + 1` function will return a numeric value representing the Day of the Week (Sunday, Monday, etc) and not the date (the number of calendar days into the current month)

For a real world example, today is Saturday, June 18th, 2016.  I just generated a token using your example code and it generated:

```
1:16:160607:test::3YJD40ss:118596
```
The datestamp SHOULD be `160618` but as you can see it is `160607` which represents `2016`, June `06`, and `07` for SATURDAY (day `06` + 1)

http://www.w3schools.com/jsref/jsref_getDay.asp
http://www.w3schools.com/jsref/jsref_getdate.asp

I think you want the following instead:

```
base_cash += formatLength2((date.getDate()).toString());
```

I'm kind of amazed that this bug has sat dormant for 4 years without anyone noticing since it is such a critical part of using hashcash tokens.  Without this change anyone who actually verifies the timestamp will likely find it to be expired immediately after generation if they run this code after the first week of the month.  Only if you tested for really long expirations (e.g. valid if within 30 days of token generation) would you be able to use the tokens generated by this library reliably.

**Comment by dpk** [comment]
I’m surprised I missed this when I was actually using this. Thanks!
